# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  routing_loader:
    default_format: json
    include_format: false
  body_listener: true
  format_listener:
    rules:
      - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }
  param_fetcher_listener: true
  access_denied_listener:
    json: true
  view:
    view_response_listener: 'force'
    formats:
      json: true
fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address:        resetting@example.com
    sender_name:    Demo Resetting
fos_oauth_server:
  db_driver: orm
  client_class:        App\Entity\Client
  access_token_class:  App\Entity\AccessToken
  refresh_token_class: App\Entity\RefreshToken
  auth_code_class:     App\Entity\AuthCode
  service:
    user_provider: fos_user.user_provider.username
    options:
      access_token_lifetime: 86400
      refresh_token_lifetime: 1209600
      auth_code_lifetime: 30